// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for Message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1NZXNzYWdlLnByb3RvIpcBCgVNb2RlbBIKCgJpZBgBIAEoAxIOCgZhY3Rp",
          "b24YAiABKAkSDwoHY29udGVudBgDIAEoCRIOCgZzZW5kZXIYBCABKAkSEAoI",
          "cmVjZWl2ZXIYBSABKAkSDQoFZXh0cmEYBiABKAkSDQoFdGl0bGUYByABKAkS",
          "DgoGZm9ybWF0GAggASgJEhEKCXRpbWVzdGFtcBgJIAEoA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Model), global::Model.Parser, new[]{ "Id", "Action", "Content", "Sender", "Receiver", "Extra", "Title", "Format", "Timestamp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Model : pb::IMessage<Model> {
  private static readonly pb::MessageParser<Model> _parser = new pb::MessageParser<Model>(() => new Model());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Model> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Model() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Model(Model other) : this() {
    id_ = other.id_;
    action_ = other.action_;
    content_ = other.content_;
    sender_ = other.sender_;
    receiver_ = other.receiver_;
    extra_ = other.extra_;
    title_ = other.title_;
    format_ = other.format_;
    timestamp_ = other.timestamp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Model Clone() {
    return new Model(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "action" field.</summary>
  public const int ActionFieldNumber = 2;
  private string action_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Action {
    get { return action_; }
    set {
      action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "content" field.</summary>
  public const int ContentFieldNumber = 3;
  private string content_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Content {
    get { return content_; }
    set {
      content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sender" field.</summary>
  public const int SenderFieldNumber = 4;
  private string sender_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Sender {
    get { return sender_; }
    set {
      sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "receiver" field.</summary>
  public const int ReceiverFieldNumber = 5;
  private string receiver_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Receiver {
    get { return receiver_; }
    set {
      receiver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "extra" field.</summary>
  public const int ExtraFieldNumber = 6;
  private string extra_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Extra {
    get { return extra_; }
    set {
      extra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "title" field.</summary>
  public const int TitleFieldNumber = 7;
  private string title_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Title {
    get { return title_; }
    set {
      title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "format" field.</summary>
  public const int FormatFieldNumber = 8;
  private string format_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Format {
    get { return format_; }
    set {
      format_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 9;
  private long timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Model);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Model other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Action != other.Action) return false;
    if (Content != other.Content) return false;
    if (Sender != other.Sender) return false;
    if (Receiver != other.Receiver) return false;
    if (Extra != other.Extra) return false;
    if (Title != other.Title) return false;
    if (Format != other.Format) return false;
    if (Timestamp != other.Timestamp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Action.Length != 0) hash ^= Action.GetHashCode();
    if (Content.Length != 0) hash ^= Content.GetHashCode();
    if (Sender.Length != 0) hash ^= Sender.GetHashCode();
    if (Receiver.Length != 0) hash ^= Receiver.GetHashCode();
    if (Extra.Length != 0) hash ^= Extra.GetHashCode();
    if (Title.Length != 0) hash ^= Title.GetHashCode();
    if (Format.Length != 0) hash ^= Format.GetHashCode();
    if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Action.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Action);
    }
    if (Content.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Content);
    }
    if (Sender.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Sender);
    }
    if (Receiver.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Receiver);
    }
    if (Extra.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Extra);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Title);
    }
    if (Format.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Format);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(Timestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Action.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
    }
    if (Content.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
    }
    if (Sender.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
    }
    if (Receiver.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Receiver);
    }
    if (Extra.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Extra);
    }
    if (Title.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
    }
    if (Format.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Format);
    }
    if (Timestamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Model other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Action.Length != 0) {
      Action = other.Action;
    }
    if (other.Content.Length != 0) {
      Content = other.Content;
    }
    if (other.Sender.Length != 0) {
      Sender = other.Sender;
    }
    if (other.Receiver.Length != 0) {
      Receiver = other.Receiver;
    }
    if (other.Extra.Length != 0) {
      Extra = other.Extra;
    }
    if (other.Title.Length != 0) {
      Title = other.Title;
    }
    if (other.Format.Length != 0) {
      Format = other.Format;
    }
    if (other.Timestamp != 0L) {
      Timestamp = other.Timestamp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Action = input.ReadString();
          break;
        }
        case 26: {
          Content = input.ReadString();
          break;
        }
        case 34: {
          Sender = input.ReadString();
          break;
        }
        case 42: {
          Receiver = input.ReadString();
          break;
        }
        case 50: {
          Extra = input.ReadString();
          break;
        }
        case 58: {
          Title = input.ReadString();
          break;
        }
        case 66: {
          Format = input.ReadString();
          break;
        }
        case 72: {
          Timestamp = input.ReadInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
